CREATE SEQUENCE SEQ_COUNTRY
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  MAXVALUE 9999999;

CREATE TABLE T_COUNTRY 
   (	
	KEY INTEGER NOT NULL, 
	NAME VARCHAR(20), 
	CODE VARCHAR(20),
	CAPITAL VARCHAR(20),
   );

ALTER TABLE T_COUNTRY
ADD CONSTRAINT PK_COUNTRY PRIMARY KEY (KEY);