CREATE TABLE T_CONTINENT 
   (	
	CONTINENT_ID INTEGER NOT NULL,
	NAME VARCHAR(20), 
	CODE VARCHAR(20),
	SIZE INTEGER
   );
   
ALTER TABLE T_CONTINENT
ADD CONSTRAINT PK_CONTINENT PRIMARY KEY (CONTINENT_ID);   