CREATE TABLE T_STATES 
   (	
	STATE_ID INTEGER NOT NULL, 
	COUNTRY_ID INTEGER NOT NULL,
	NAME VARCHAR(20), 
	CODE VARCHAR(20),
	POPULATION INTEGER
   );

ALTER TABLE T_STATES
ADD FOREIGN KEY (COUNTRY_ID) REFERENCES T_COUNTRY(KEY);