CREATE TABLE T_AUTOMOBILE
   (	
	ID INTEGER NOT NULL, 
	NAME VARCHAR(20), 
	TYPE VARCHAR(20),
	ENGINE_ID INTEGER
   );

ALTER TABLE T_AUTOMOBILE
ADD CONSTRAINT PK_AUTOMOBILE PRIMARY KEY (ID);

CREATE TABLE T_ENGINE
   (	
	ID INTEGER NOT NULL, 
	TYPE VARCHAR(20)
   );

ALTER TABLE T_ENGINE
ADD CONSTRAINT PK_ENGINE PRIMARY KEY (ID);
   
ALTER TABLE T_AUTOMOBILE
ADD FOREIGN KEY (ENGINE_ID) REFERENCES T_ENGINE(ID);
